name: CI Practice

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use practice secret
        env:
          PRACTICE_SECRET: ${{ secrets.PRACTICE_SECRET }}
        run: |
          if [ -n "$PRACTICE_SECRET" ]; then
            echo "Secret is available and being used."
          else
            echo "Secret is not available."
            exit 1
          fi
